CFLAGS = -

SOURCE = vowelshift

all: $(SOURCE)

vowelshift: vowelshift.c
	gcc $(CFLAG) vowelshift.c -o vowelshift

stringoperations: stringoperations.c test.c
	gcc $(CFLAG) stringoperations.c test.c -o vowelshift

clean:
	rm -f